import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  const password = await bcrypt.hash("abogado123", 10);
  const specialPassword = await bcrypt.hash("123", 10);

  const lawyers = [
    {
      firstName: "Martin",
      lastName: "Rodriguez",
      email: "yo@gmail.com",
      password: specialPassword,
      phone: "223-456-7890",
      matricula: "MDP-14523",
      specialties: "Derecho Penal,Derecho Civil",
      province: "Buenos Aires",
      city: "Mar del Plata",
      address: "Av. Colon 2345, Centro",
      latitude: -38.0055,
      longitude: -57.5426,
      narrative: "Abogado penalista con mas de 12 anos de experiencia en litigios penales y civiles. Especializado en defensa penal y juicios por danos y perjuicios.",
      experience: "12 anos de ejercicio profesional. Ex fiscal adjunto del Departamento Judicial Mar del Plata. Docente de Derecho Penal en la UNMDP.",
      cbuAlias: "martin.rodriguez.mdp",
      status: "approved",
      rating: 4.8,
      reviewCount: 24,
      subscriptionStatus: "active",
    },
    {
      firstName: "Carolina",
      lastName: "Fernandez",
      email: "carolina.fernandez@legal.com",
      password,
      phone: "223-567-1234",
      matricula: "MDP-18976",
      specialties: "Derecho de Familia,Derecho Civil",
      province: "Buenos Aires",
      city: "Mar del Plata",
      address: "San Martin 3456, Centro",
      latitude: -38.0023,
      longitude: -57.5482,
      narrative: "Especialista en derecho de familia, divorcios, tenencia y alimentos. Enfoque humano y resolucion de conflictos familiares.",
      experience: "8 anos de ejercicio. Mediadora matriculada. Miembro del Colegio de Abogados de Mar del Plata.",
      cbuAlias: "caro.fernandez.abogada",
      status: "approved",
      rating: 4.9,
      reviewCount: 31,
      subscriptionStatus: "active",
    },
    {
      firstName: "Lucas",
      lastName: "Gomez",
      email: "lucas.gomez@legal.com",
      password,
      phone: "223-678-2345",
      matricula: "MDP-21034",
      specialties: "Derecho Laboral",
      province: "Buenos Aires",
      city: "Mar del Plata",
      address: "Av. Independencia 1890, La Perla",
      latitude: -38.0142,
      longitude: -57.5345,
      narrative: "Defensor de los derechos del trabajador. Especializado en despidos, accidentes laborales, ART y reclamos sindicales.",
      experience: "10 anos de ejercicio en derecho laboral. Representante de sindicatos locales. Mas de 500 casos resueltos a favor del trabajador.",
      cbuAlias: "lucas.gomez.laboral",
      status: "approved",
      rating: 4.6,
      reviewCount: 18,
      subscriptionStatus: "active",
    },
    {
      firstName: "Valentina",
      lastName: "Lopez",
      email: "valentina.lopez@legal.com",
      password,
      phone: "223-789-3456",
      matricula: "MDP-15678",
      specialties: "Derecho Comercial,Derecho Tributario",
      province: "Buenos Aires",
      city: "Mar del Plata",
      address: "Belgrano 2678, Guemes",
      latitude: -38.0098,
      longitude: -57.5512,
      narrative: "Asesora empresarial y tributaria. Ayudo a empresas y emprendedores a operar dentro del marco legal y optimizar su carga fiscal.",
      experience: "15 anos en derecho comercial y tributario. Asesora de la Camara de Comercio de Mar del Plata. Especialista en sociedades y contratos.",
      cbuAlias: "vale.lopez.tributario",
      status: "approved",
      rating: 4.7,
      reviewCount: 22,
      subscriptionStatus: "active",
    },
    {
      firstName: "Santiago",
      lastName: "Martinez",
      email: "santiago.martinez@legal.com",
      password,
      phone: "223-890-4567",
      matricula: "MDP-22341",
      specialties: "Derecho Inmobiliario,Derecho Civil",
      province: "Buenos Aires",
      city: "Mar del Plata",
      address: "Av. Luro 4567, Centro",
      latitude: -38.0001,
      longitude: -57.5456,
      narrative: "Especialista en operaciones inmobiliarias, escrituras, usucapion y conflictos de propiedad. Acompano cada transaccion de principio a fin.",
      experience: "9 anos en derecho inmobiliario. Escribano asociado. Asesor de inmobiliarias y constructoras de la zona.",
      cbuAlias: "santi.martinez.inmob",
      status: "approved",
      rating: 4.5,
      reviewCount: 15,
      subscriptionStatus: "active",
    },
    {
      firstName: "Florencia",
      lastName: "Diaz",
      email: "florencia.diaz@legal.com",
      password,
      phone: "223-901-5678",
      matricula: "MDP-19887",
      specialties: "Derecho Administrativo,Derecho Ambiental",
      province: "Buenos Aires",
      city: "Mar del Plata",
      address: "Av. Juan B Justo 6789, Punta Mogotes",
      latitude: -38.0312,
      longitude: -57.5287,
      narrative: "Derecho publico y ambiental. Defiendo los derechos de los ciudadanos frente al Estado y trabajo en proteccion ambiental costera.",
      experience: "7 anos de ejercicio. Asesora ambiental del municipio. Litigante en causas de interes publico.",
      cbuAlias: "flor.diaz.ambiental",
      status: "approved",
      rating: 4.4,
      reviewCount: 12,
      subscriptionStatus: "active",
    },
    {
      firstName: "Nicolas",
      lastName: "Perez",
      email: "nicolas.perez@legal.com",
      password,
      phone: "223-012-6789",
      matricula: "MDP-24567",
      specialties: "Derecho Informatico,Derecho Comercial",
      province: "Buenos Aires",
      city: "Mar del Plata",
      address: "Catamarca 1234, Centro",
      latitude: -38.0078,
      longitude: -57.5398,
      narrative: "Abogado tech. Proteccion de datos personales, contratos digitales, comercio electronico y ciberdelitos. El futuro del derecho es digital.",
      experience: "5 anos en derecho informatico. Certificado en proteccion de datos (AAIP). Asesor de startups y empresas tecnologicas.",
      cbuAlias: "nico.perez.tech",
      status: "approved",
      rating: 4.3,
      reviewCount: 9,
      subscriptionStatus: "active",
    },
    {
      firstName: "Camila",
      lastName: "Torres",
      email: "camila.torres@legal.com",
      password,
      phone: "223-123-7890",
      matricula: "MDP-17654",
      specialties: "Derecho Penal,Derecho de Familia",
      province: "Buenos Aires",
      city: "Mar del Plata",
      address: "Alem 3456, Puerto",
      latitude: -38.0189,
      longitude: -57.5267,
      narrative: "Abogada comprometida con la justicia social. Especialista en violencia de genero, proteccion de menores y derecho penal juvenil.",
      experience: "11 anos de ejercicio. Patrocinante de la ONG Mujeres Libres. Ex asesora de menores.",
      cbuAlias: "cami.torres.justicia",
      status: "approved",
      rating: 4.9,
      reviewCount: 28,
      subscriptionStatus: "active",
    },
    // --- 2 PENDIENTES ---
    {
      firstName: "Federico",
      lastName: "Sanchez",
      email: "federico.sanchez@legal.com",
      password,
      phone: "223-234-8901",
      matricula: "MDP-26789",
      specialties: "Derecho Laboral,Derecho de Seguros",
      province: "Buenos Aires",
      city: "Mar del Plata",
      address: "Rivadavia 5678, Constitucion",
      latitude: -38.0134,
      longitude: -57.5567,
      narrative: "Abogado laboralista y de seguros. Busco justicia para quienes sufren accidentes y necesitan cobrar lo que les corresponde.",
      experience: "6 anos de ejercicio. Especialista en ART y seguros de vida.",
      cbuAlias: "fede.sanchez.seguros",
      status: "pending",
      rating: 0,
      reviewCount: 0,
      subscriptionStatus: "pending",
    },
    {
      firstName: "Maria",
      lastName: "Aguirre",
      email: "maria.aguirre@legal.com",
      password,
      phone: "223-345-9012",
      matricula: "MDP-28901",
      specialties: "Derecho Migratorio,Derecho Civil",
      province: "Buenos Aires",
      city: "Mar del Plata",
      address: "Av. Paso 2345, Don Bosco",
      latitude: -38.0215,
      longitude: -57.5489,
      narrative: "Asesora migratoria. Ayudo a extranjeros con radicaciones, ciudadania, permisos de trabajo y todo tramite migratorio en Argentina.",
      experience: "4 anos en derecho migratorio. Interprete de portugues e ingles. Voluntaria en ACNUR.",
      cbuAlias: "maria.aguirre.migra",
      status: "pending",
      rating: 0,
      reviewCount: 0,
      subscriptionStatus: "pending",
    },
  ];

  for (const lawyer of lawyers) {
    const existing = await prisma.lawyer.findUnique({ where: { email: lawyer.email } });
    if (existing) {
      await prisma.lawyer.update({ where: { email: lawyer.email }, data: lawyer });
      console.log(`Updated: ${lawyer.firstName} ${lawyer.lastName}`);
    } else {
      await prisma.lawyer.create({ data: lawyer });
      console.log(`Created: ${lawyer.firstName} ${lawyer.lastName}`);
    }
  }

  console.log("\nSeed completed: 10 lawyers in Mar del Plata (8 approved, 2 pending)");
  console.log("Login especial: yo@gmail.com / 123");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
